export enum ErrorCode {
  // Auth
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',

  // Users
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',

  // Credits
  INSUFFICIENT_CREDITS = 'INSUFFICIENT_CREDITS',
  PACKAGE_NOT_FOUND = 'PACKAGE_NOT_FOUND',
  INVALID_CREDIT_AMOUNT = 'INVALID_CREDIT_AMOUNT',
  CREDIT_TRANSACTION_FAILED = 'CREDIT_TRANSACTION_FAILED',

  // GenAI
  GENERATION_FAILED = 'GENERATION_FAILED',
  INVALID_PROMPT = 'INVALID_PROMPT',

  // Generic
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  NOT_FOUND = 'NOT_FOUND',
}
